### ISSUE TITLE
Outputs files but gives error (10.0.0.4)

### ISSUE THREAD

**Issue by billygijoe** [suchmememanyskill/EmmcHaccGen#2] opened 2020-07-01 22:55 UTC
net core framework is installed (windowsdesktop-runtime-3.1.5-win-x64.exe, includes core framework.)

not sure if safe to install, even though it output files.
```
C:\Windows\system32>C:\Users\<user>\Downloads\EmmcHaccGen.2.2.1\EmmcHaccGen.exe --fw "C:\Users\<user>\Downloads\Firmware 10.0.4" --keys C:\Users\<user>\Downloads\keys.txt
EmmcHaccGen started
Indexing nca files...
[Warning] Version extraction failed. Version is unknown

EmmcHaccGen will now generate firmware files using the following settings:
fw: NX-Unkn
Exfat Support: True
Key path: C:\Users\<user>\Downloads\keys.txt
Destination folder: NX-Unkn_exFAT


Creating folders..
Destenation folder already exists. Delete the old folder?
Y/N: y
Deleting NX-Unkn_exFAT

Generating bis..
Wrote 0x00180000 bytes to NX-Unkn_exFAT/BOOT0.bin
Wrote 0x00080000 bytes to NX-Unkn_exFAT/BOOT1.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-1-Normal-Main.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-2-Normal-Sub.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-3-SafeMode-Main.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-4-SafeMode-Sub.bin
Wrote 0x01200025 bytes to NX-Unkn_exFAT/boot.bis

Copying files...

Setting archive bits..

Generating imkvdb..
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not find file 'C:\Windows\system32\save.stub'.
File name: 'C:\Windows\system32\save.stub'
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at EmmcHaccGen.Program.Start(String keys, String fwPath, Boolean noExfat, Boolean verbose, Boolean showNcaIndex, Boolean fixHashes)
   at EmmcHaccGen.Program.Main(String keys, String fw, Boolean noExfat, Boolean verbose, Boolean showNcaIndex, Boolean fixHashes)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass6_0.<<ConfigureConsole>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**EDIT:**  I CD'd to the exes' directory but still shows a bunch of red text

```
C:\Windows\system32>cd C:\Users\<user>\Downloads\EmmcHaccGen.2.2.1

C:\Users\<user>\Downloads\EmmcHaccGen.2.2.1>C:\Users\<user>\Downloads\EmmcHaccGen.2.2.1\EmmcHaccGen.exe --fw "C:\Users\<user>\Downloads\Firmware 10.0.4" --keys C:\Users\<user>\Downloads\keys.txt
EmmcHaccGen started
Indexing nca files...
[Warning] Version extraction failed. Version is unknown

EmmcHaccGen will now generate firmware files using the following settings:
fw: NX-Unkn
Exfat Support: True
Key path: C:\Users\<user>\Downloads\keys.txt
Destination folder: NX-Unkn_exFAT


Creating folders..

Generating bis..
Wrote 0x00180000 bytes to NX-Unkn_exFAT/BOOT0.bin
Wrote 0x00080000 bytes to NX-Unkn_exFAT/BOOT1.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-1-Normal-Main.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-2-Normal-Sub.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-3-SafeMode-Main.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-4-SafeMode-Sub.bin
Wrote 0x01200025 bytes to NX-Unkn_exFAT/boot.bis

Copying files...

Setting archive bits..

Generating imkvdb..
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.HorizonResultException: ResultFsPreconditionViolation (2002-6000)
   at LibHac.ThrowHelper.ThrowResult(Result result)
   at EmmcHaccGen.Program.Start(String keys, String fwPath, Boolean noExfat, Boolean verbose, Boolean showNcaIndex, Boolean fixHashes)
   at EmmcHaccGen.Program.Main(String keys, String fw, Boolean noExfat, Boolean verbose, Boolean showNcaIndex, Boolean fixHashes)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass6_0.<<ConfigureConsole>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

![image](https://user-images.githubusercontent.com/40858180/86298378-9c1b2000-bbcb-11ea-8481-4255b5832008.png)

**Comment by billygijoe** [comment] 2020-07-01 22:59
Also tried 10.0.0.2, might be same error though.

Also, nitpick about spelling:

> Creating folders..
> Destenation folder already exists. Delete the old folder?


Thanks!

```
C:\Windows\system32>C:\Users\<user>\Downloads\EmmcHaccGen.2.2.1\EmmcHaccGen.exe --fw "C:\Users\<user>\Downloads\EmmcHaccGen.2.2.1\Firmware 10.0.2" --keys C:\Users\<user>\Downloads\keys.txt
EmmcHaccGen started
Indexing nca files...
[Warning] Version extraction failed. Version is unknown

EmmcHaccGen will now generate firmware files using the following settings:
fw: NX-Unkn
Exfat Support: True
Key path: C:\Users\<user>\Downloads\keys.txt
Destination folder: NX-Unkn_exFAT


Creating folders..
Destenation folder already exists. Delete the old folder?
Y/N: y
Deleting NX-Unkn_exFAT

Generating bis..
Wrote 0x00180000 bytes to NX-Unkn_exFAT/BOOT0.bin
Wrote 0x00080000 bytes to NX-Unkn_exFAT/BOOT1.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-1-Normal-Main.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-2-Normal-Sub.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-3-SafeMode-Main.bin
Wrote 0x00800000 bytes to NX-Unkn_exFAT/BCPKG2-4-SafeMode-Sub.bin
Wrote 0x01200025 bytes to NX-Unkn_exFAT/boot.bis

Copying files...

Setting archive bits..

Generating imkvdb..
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not find file 'C:\Windows\system32\save.stub'.
File name: 'C:\Windows\system32\save.stub'
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at EmmcHaccGen.Program.Start(String keys, String fwPath, Boolean noExfat, Boolean verbose, Boolean showNcaIndex, Boolean fixHashes)
   at EmmcHaccGen.Program.Main(String keys, String fw, Boolean noExfat, Boolean verbose, Boolean showNcaIndex, Boolean fixHashes)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass6_0.<<ConfigureConsole>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by suchmememanyskill** [comment] 2020-07-02 08:35
Hi, you seem to be a bit inexperienced with using commandlline applications. It's looking for save.stub in your current path, which is not the same folder emmchaccgen is in. cd into the emmchaccgen folder by typing `cd C:\Users\<user>\Downloads\EmmcHaccGen.2.2.1` then type in `emmchaccgen.exe --fw "..\Firmware 10.0.4" --keys ..\keys.txt`

I'm also kinda concerned on you having a keys.txt in your downloads folder. Is this your prod.keys? (It needs to be if you want to restore the SYSTEM folder)

Oh also to answer your question of "is it safe to install", not if you're planning to restore the system folder. The binary files should be fine

**Comment by billygijoe** [comment] 2020-07-07 00:37
Hey, sorry for the delay, I edited the original post to point out that I
did indeed also try cd’ing into the folder, probably should have made it a
reply though

I’ll be 100% honest, My switch was acting up so I wanted a fresh start (new
firmware too), and grabbed a keys file from the net, glad I asked though,
sorry for the trouble. I have like 6 switch nand backups all over my hard
drive and didnt want to dig through it to find the keys file, or figure
which damn payloader to do what with lol

——————————————

Honestly this can be closed probably, I ended up using choidujournx (it’s
been months since I used my switch, I was kinda rusty on the details)

**Comment by suchmememanyskill** [comment] 2020-07-07 00:47
First of all, to get your console's keys you should've used lockpickrcm. 

Second, if you want a fresh start this application is **not the way to go**. This should strictly be used in (un)bricking or pc side update/downgrade generation scenarios. To get a fresh start, [you can also wipe the system](https://suchmememanyskill.github.io/guides/unbrick/#system-wipe).

Also the latest error while cd'd into the folder seems to be caused by it not being able to sign the save, which well, is not yours, so it probably won't work.

Anyway, as there is no longer an issue, i'll close this

**Closed as completed** 2020-07-07 00:48 UTC
